[package]
name = "flipclock-rs"
version = "0.1.0"
edition = "2024"


[dependencies]
sdl2 = { version = "0.37", features = ["ttf"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
dirs = "6.0"
thiserror = "2.0"


[build-dependencies]
pkg-config = "0.3"
